### ISSUE TITLE
Create a "Deploy to Heroku" Button

### ISSUE THREAD

**Issue by wbeard** [aptotude/circle-build-health#3]
In an effort to diversify the number of environments in which this can run, I'd like to add a "Deploy to Heroku" button in the README.

Here's an article, from heroku, on how to do this - https://devcenter.heroku.com/articles/heroku-button.

Thanks!

**Comment by jboxman** [comment]
Hi. I've used Heroku in the past, so it's somewhat credible I can complete this.

**Comment by jboxman** [comment]
Didn't realize this was completed in https://github.com/aptotude/circle-build-health/pull/8

**Comment by wbeard** [comment]
@jboxman I'd be happy to close that PR so others can contribute!
